name: compare_swe
#channels:
#  - javascript
dependencies:
  - python=3.9
  - geopandas
  - shapely
  - folium
  - pandas
  - matplotlib
  - cartopy
  - regionmask
  - xarray
  - numpy
  - pytorch
  - pip
  - netcdf4
  - jupyter
  - pyprojroot
  - dask
  - geojson
  - pip:
      - glob2
